import Moment from "moment";

export const EDIT_PROJECT_FORM_CONFIG = [
  {
    id: "title",
    type: "textfield",
    defaultValue: "",
    formLabel: "Project Name",
    placeholder: "Project Name",
    isError: false,
    isReq: true,
    isReadOnly: false,
  },
  {
    id: "projectType",
    type: "select",
    defaultValue: "",
    placeHolder: "Select",
    label: "Material (Optional)",
    isLarge: false,
    isError: false,
    isReq: true,
    isflex: false,
    isReadOnly: false,
    formLabel: "Project type",
    options: [],
  },
  {
    id: "description",
    type: "textarea",
    defaultValue: "",
    formLabel: "Description",
    placeholder: "Description",
    isError: false,
    isReq: false,
    isReadOnly: false,
  },
  {
    id: "utm",
    type: "textfield",
    defaultValue: "",
    formLabel: "UTM",
    placeholder: "UTM",
    isError: false,
    isReq: true,
    isReadOnly: false,
  },
  {
    id: "latitude",
    type: "textfield",
    defaultValue: "",
    formLabel: "Latitude",
    placeholder: "Latitude",
    isError: false,
    isReq: true,
    isReadOnly: false,
  },
  {
    id: "longitude",
    type: "textfield",
    defaultValue: "",
    formLabel: "Longitude",
    placeholder: "Longitude",
    isError: false,
    isReq: true,
    isReadOnly: false,
  },
];
