import JSGantt from 'jsgantt-improved';
import task from '../projectGantt.json';
export function MyComponent() {
  const ganttChartDiv = document.getElementById('GanttChartDIV');

  if (!ganttChartDiv) {
    console.error('Gantt chart element not found');
    return null;
  }
  var g = new JSGantt.GanttChart(ganttChartDiv, 'week');
  g.setEditable(true);
  g.setShowRes(0),
    g.setOptions({
      vCaptionType: 'Complete',
      vQuarterColWidth: 36,
      vDateTaskDisplayFormat: 'day dd month yyyy',
      vDayMajorDateDisplayFormat: 'mon yyyy - Week ww',
      vWeekMinorDateDisplayFormat: 'dd mon',
      vLang: 'en',
      vShowTaskInfoLink: 1,
      vShowEndWeekDate: 0,
      vUseSingleCell: 10000,
      vFormatArr: ['Day', 'Week', 'Month', 'Quarter', 'Year'],
      vScrollTo: new Date(),
    });
  JSGantt.parseJSONString(JSON.stringify(task), g);
  g.Draw();
  // const groupTasks = [
  //   {
  //     pID: 'task01',
  //     pName: "<a href='http://www.baidu.com'>data</a>",
  //     pStart: '',
  //     pEnd: '',
  //     pPlanStart: '',
  //     pPlanEnd: '',
  //     pClass: 'ggroupblack',
  //     pLink: "<a href='#'>fdjkjdf</a>",
  //     pMile: 0,
  //     pRes: 'ffeksdl',
  //     pComp: 0,
  //     pGroup: 1,
  //     pParent: 0,
  //     pOpen: 1,
  //     pDepend: '',
  //     pCaption: '',
  //     pCost: 0,
  //     pNotes: 'this is notes',
  //     pBarText: '任务名称',
  //     customColumn1: 'abc',
  //     customColumn2: `customColumn2`,
  //   },
  //   {
  //     pID: 'task02',
  //     pName: '测试子任务',
  //     pStart: '2020-02-15',
  //     pEnd: '2020-02-21',
  //     pPlanStart: '2020-02-01',
  //     pPlanEnd: '2020-02-20',
  //     pClass: 'gtaskblue',
  //     pLink: '',
  //     pMile: 0,
  //     pRes: "<a href='#' title='测试子任务资源'>测试子任务资源</a>",
  //     pComp: 30,
  //     pGroup: 0,
  //     pParent: 'task01',
  //     pOpen: 0,
  //     pDepend: '',
  //     pCaption: '',
  //     pCost: 1000,
  //     pNotes: 'pNotes',
  //     pBarText: '测试子任务',
  //     customColumn1: 'a',
  //     customColumn2: 'a',
  //   },
  //   {
  //     pID: 'task03',
  //     pName: '测试关联任务1',
  //     pStart: '2020-01-01',
  //     pEnd: '2020-01-21',
  //     pPlanStart: '2020-01-01',
  //     pPlanEnd: '2020-01-20',
  //     pClass: 'gtaskyellow',
  //     pLink: '',
  //     pMile: 0,
  //     pRes: '测试关联任务1资源',
  //     pComp: 0,
  //     pGroup: 0,
  //     pParent: 'task01',
  //     pOpen: 0,
  //     pDepend: 'task02',
  //     pCaption: '',
  //     pCost: 1000,
  //     pNotes: 'pNotes',
  //     pBarText: '测试关联任务1',
  //     customColumn1: 'b',
  //     customColumn2: 'd',
  //   },
  //   {
  //     pID: 'task04',
  //     pName: '测试关联任务2',
  //     pStart: '2020-01-15',
  //     pEnd: '2020-01-21',
  //     pPlanStart: '2020-01-05',
  //     pPlanEnd: '2020-01-18',
  //     pClass: 'gtaskred',
  //     pLink: '',
  //     pMile: 0,
  //     pRes: '测试关联任务2资源',
  //     pComp: 0,
  //     pGroup: 0,
  //     pParent: 'task01',
  //     pOpen: 0,
  //     pDepend: 'task02,task03',
  //     pCaption: '',
  //     pCost: 1000,
  //     pNotes: 'pNotes',
  //     pBarText: '测试关联任务2',
  //     customColumn1: 'd',
  //     customColumn2: 'd',
  //   },
  // ];
}
