export const SIGN_UP_FORM_CONFIG = [
  {
    id: "email",
    type: "textfield",
    defaultValue: "",
    // formLabel: "What shall we call this issue?",
    placeholder: "Email ID",
    isError: false,
    isReq: true,
    isValidField: false,
    isReadOnly: false,
    imageIcon: "emailIcon",
    errorMsg: "",
    showErrorMsg: false,
  },
  {
    id: "password",
    type: "password",
    defaultValue: "",
    // formLabel: "What shall we call this issue?",
    placeholder: "Enter Password",
    isError: false,
    isReq: true,
    isReadOnly: false,
    imageIcon: "passwordIcon",
    errorMsg: "",
    showErrorMsg: false,
    isValidField: false,
  },

  {
    id: "create_password",
    type: "password",
    defaultValue: "",
    // formLabel: "What shall we call this issue?",
    placeholder: "Create Password",
    isError: false,
    isReq: true,
    isReadOnly: false,
    imageIcon: "passwordIcon",
    errorMsg: "",
    showErrorMsg: false,
    isValidField: false,
  },

  //   {
  //     id: "title",
  //     type: "loginPasswordField",
  //     defaultValue: "",
  //     placeholder: "Enter Password",
  //     isError: false,
  //     isReq: true,
  //     isReadOnly: false,
  //   }
];
